# Generated by Django 2.2.4 on 2020-04-08 11:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200408_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 11, 3, 56, 531217, tzinfo=utc)),
        ),
    ]
