# Generated by Django 2.2.4 on 2020-04-09 17:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200408_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 17, 12, 40, 160146, tzinfo=utc)),
        ),
    ]
