# Generated by Django 2.2.4 on 2020-04-10 06:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200409_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 6, 5, 22, 818209, tzinfo=utc)),
        ),
    ]
