# Generated by Django 2.2.4 on 2020-04-10 06:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200410_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 6, 19, 30, 484984, tzinfo=utc)),
        ),
    ]
